import type {
  RothConversionOtherAsset,
  RothIraOnboardingValues,
  SoloParticipant,
  TraditionalBeneficiary,
  TraditionalInterestedPartyIndividual,
} from './RothIraOnboardingFlow.types'
import { createEmptySoloParticipant } from './RothIraOnboardingFlow.constants'

interface InitialValuesOptions {
  isTraditionalIra: boolean
}

export const createInitialRothIraValues = ({ isTraditionalIra }: InitialValuesOptions): RothIraOnboardingValues => ({
  firstName: '',
  middleName: '',
  lastName: '',
  dateOfBirth: '',
  ssn: '',
  citizenship: '',
  maritalStatus: '',
  employmentStatus: '',
  email: '',
  phone: '',
  mailingStreet: '',
  mailingAddress2: '',
  mailingCity: '',
  mailingState: '',
  mailingZip: '',
  sameAsPhysicalAddress: true,
  statementDelivery: 'electronic',
  taxFormDelivery: 'electronic',
  electronicConsent: false,
  w9Consent: false,
  primaryBeneficiaryName: '',
  primaryBeneficiaryRelationship: '',
  primaryBeneficiaryDob: '',
  primaryBeneficiarySsn: '',
  primaryBeneficiaryPercent: '',
  addContingentBeneficiary: false,
  hasInterestedParty: false,
  interestedPartyName: '',
  interestedPartyRelationship: '',
  interestedPartyEmail: '',
  interestedPartyPhone: '',
  paymentMethod: 'card',
  nameOnCard: '',
  cardNumber: '',
  cardExpiry: '',
  cardCvc: '',
  acceptAgreement: false,
  fundingOption: isTraditionalIra ? 'transfer' : 'new-contribution',
  fundingAmount: '',
  fundingTimeline: '',
  signed: false,
  paymentCompleted: false,
  referralSource: '',
  promoCode: '',
  salesRepresentative: '',
  physicalResidentialAddress: '',
  primaryPhoneType: 'cell',
  primaryPhoneNumber: '',
  birthMonth: '',
  birthDay: '',
  birthYear: '',
  gender: 'male',
  showSecondaryPhone: false,
  secondaryPhoneType: 'home',
  secondaryPhoneNumber: '',
  showAlternativeMailingAddress: false,
  alternativeMailingStreet: '',
  alternativeMailingAddress2: '',
  alternativeMailingCity: '',
  alternativeMailingState: '',
  alternativeMailingZip: '',
  kidFirstName: '',
  kidMiddleName: '',
  kidLastName: '',
  kidSsn: '',
  kidBirthMonth: '',
  kidBirthDay: '',
  kidBirthYear: '',
  kidGender: 'male',
  kidCitizenship: 'us',
  kidContactSameAsParent: false,
  kidPhysicalResidentialAddress: '',
  sepBeneficiaryName: '',
  sepCollectiveBargainingCovered: 'yes',
  sepNonresidentAliens: 'yes',
  sepCompensationUnder750: 'yes',
  hsaCoverage: 'individual',
  hsaInsuranceType: 'active-hdhp',
  coverdellEsaType: 'new',
  coverdellFirstName: '',
  coverdellMiddleName: '',
  coverdellLastName: '',
  coverdellSsn: '',
  coverdellBirthMonth: '',
  coverdellBirthDay: '',
  coverdellBirthYear: '',
  coverdellGender: 'male',
  coverdellCitizenship: 'us',
  successorFirstName: '',
  successorMiddleName: '',
  successorLastName: '',
  successorSsn: '',
  successorBirthMonth: '',
  successorBirthDay: '',
  successorBirthYear: '',
  successorSameAsResponsible: true,
  successorRelationship: '',
  successorPhone: '',
  successorAddress: '',
  ownerDeathMonth: '',
  ownerDeathDay: '',
  ownerDeathYear: '',
  inheritedSetupType: 'new',
  inheritedFirstName: '',
  inheritedMiddleName: '',
  inheritedLastName: '',
  inheritedSsn: '',
  inheritedBirthMonth: '',
  inheritedBirthDay: '',
  inheritedBirthYear: '',
  inheritedGender: 'male',
  inheritedCitizenship: 'us',
  inheritedRelationToDeceasedOwner: 'spouse',
  rothConversionHasExistingAccount: 'no',
  rothConversionType: 'full',
  rothConversionWithholding: 'no-withhold',
  soloPlanSetupOption: 'new-plan',
  soloTrustCheckingAuthorization: true,
  soloParticipantTrustee: 'yes',
  soloParticipantFirstName: '',
  soloParticipantMiddleName: '',
  soloParticipantLastName: '',
  soloParticipantAddress: '',
  soloParticipantPrimaryPhone: '',
  soloParticipantSecondaryPhone: '',
  soloParticipantEmail: '',
  soloParticipantSsn: '',
  soloParticipantBirthMonth: '',
  soloParticipantBirthDay: '',
  soloParticipantBirthYear: '',
  soloParticipantTraditionalAccount: false,
  soloParticipantRothAccount: false,
  soloParticipantAfterTaxAccount: false,
  soloEmployerCompanyName: '',
  soloEmployerEin: '',
  soloEmployerEntityType: '',
  soloEmployerAddress: '',
  soloEmployerPhone: '',
  soloEmployerEstablishedState: '',
  soloEmployerLineOfBusiness: '',
  soloEmployerOwnerPartner: '',
  soloEmployerEmployeeCount: '',
  soloEmployerHasOwnershipOtherCompany: 'yes',
  backdoorEstablishmentOption: 'new-backdoor',
  backdoorContributionYearOne: `${new Date().getFullYear()}`,
  backdoorContributionAmountOne: '',
  backdoorContributionYearTwo: `${new Date().getFullYear() - 1}`,
  backdoorContributionAmountTwo: '',
  interestedPartyCompanyAuthorized: true,
  interestedPartyCompanyName: '',
  interestedPartyCompanyEmail: '',
  retirePlanType: '401k',
  retireFundTraditional: true,
  retireFundRoth: true,
  retirePlanName: '',
  retireTaxId: '',
  retireBirthMonth: '',
  retireBirthDay: '',
  retireBirthYear: '',
  retireMailingAddress: '',
  retireTpaCompanyName: '',
  retireTpaContactName: '',
  retireTpaPrimaryPhoneType: 'cell',
  retireTpaPrimaryPhoneNumber: '',
  retireTpaEmail: '',
  rothConversionOtherHasExistingAccount: 'yes',
  rothConversionOtherInstruction: 'traditional-only',
  rothConversionOtherRothAch: '',
  rothConversionOtherType: 'partial',
  rothConversionOtherCashSelected: false,
  rothConversionOtherCashAmount: '',
  rothConversionOtherNonCashSelected: true,
})

export const createInitialTraditionalBeneficiaries = (): TraditionalBeneficiary[] => [
  {
    id: 1,
    designation: 'primary',
    beneficiaryName: '',
    relation: 'spouse',
    birthMonth: '',
    birthDay: '',
    birthYear: '',
    sharePercentage: '100',
  },
]

export const createInitialTraditionalInterestedParty = (): TraditionalInterestedPartyIndividual => ({
  firstName: '',
  middleName: '',
  lastName: '',
  taxIdOrSsn: '',
  birthMonth: '',
  birthDay: '',
  birthYear: '',
  relationship: '',
  physicalResidentialAddress: '',
  primaryPhoneType: 'cell',
  primaryPhoneNumber: '',
  emailAddress: '',
})

export const createInitialSoloParticipants = (): SoloParticipant[] => [createEmptySoloParticipant(1)]

export const createInitialRothConversionOtherAssets = (): RothConversionOtherAsset[] => [{ id: 1, assetName: '', amount: '' }]
