import { Coins, FileText, HandCoins, Landmark, PiggyBank, PlusCircle, ReceiptText } from 'lucide-react'
import { lazy, type ComponentType, type LazyExoticComponent } from 'react'

export interface ManageInvestmentOption {
  id: string
  title: string
  description: string
  icon: ComponentType<{ className?: string }>
}

export interface ManageInvestmentFlowProps {
  onBackToManageInvestments: () => void
}

export const manageInvestmentOptions = [
  {
    id: 'expense-payment-990-t',
    title: '990-T Expense Payment',
    description: 'Submit an expense payment request related to IRS Form 990-T.',
    icon: FileText,
  },
  {
    id: 'additional-investment-request',
    title: 'Additional Investment Request',
    description: 'Request additional funding for an existing investment position.',
    icon: PlusCircle,
  },
  {
    id: 'fair-market-valuation-self-certification',
    title: 'Fair Market Valuation - Self Certification',
    description: 'Provide a self-certified fair market valuation update.',
    icon: Landmark,
  },
  {
    id: 'fair-market-valuation-taxable-event',
    title: 'Fair Market Valuation - Taxable Event',
    description: 'Report a fair market valuation tied to a taxable event.',
    icon: Coins,
  },
  {
    id: 'investment-income-deposit',
    title: 'Investment Income Deposit',
    description: 'Record and deposit income generated by an existing investment.',
    icon: PiggyBank,
  },
  {
    id: 'sale-of-assets-note-payoff',
    title: 'Sale of Assets/Note Payoff',
    description: 'Submit sale proceeds or payoff details for an asset or note.',
    icon: HandCoins,
  },
  {
    id: 'expense-payment',
    title: 'Expense Payment',
    description: 'Submit a general expense payment request for an existing investment.',
    icon: ReceiptText,
  },
] as const satisfies ReadonlyArray<ManageInvestmentOption>

export type ManageInvestmentOptionId = (typeof manageInvestmentOptions)[number]['id']
type ManageInvestmentFlowComponent = LazyExoticComponent<ComponentType<ManageInvestmentFlowProps>>

export const manageInvestmentFlowComponents: Partial<Record<ManageInvestmentOptionId, ManageInvestmentFlowComponent>> = {
  'expense-payment-990-t': lazy(() =>
    import('./ExpensePayment990TFlow').then((module) => ({ default: module.ExpensePayment990TFlow })),
  ),
  'additional-investment-request': lazy(() =>
    import('./AdditionalInvestmentRequestFlow').then((module) => ({ default: module.AdditionalInvestmentRequestFlow })),
  ),
  'fair-market-valuation-self-certification': lazy(() =>
    import('./FairMarketValuationSelfCertificationFlow').then((module) => ({
      default: module.FairMarketValuationSelfCertificationFlow,
    })),
  ),
  'fair-market-valuation-taxable-event': lazy(() =>
    import('./FairMarketValuationTaxableEventFlow').then((module) => ({
      default: module.FairMarketValuationTaxableEventFlow,
    })),
  ),
  'investment-income-deposit': lazy(() =>
    import('./InvestmentIncomeDepositFlow').then((module) => ({ default: module.InvestmentIncomeDepositFlow })),
  ),
  'sale-of-assets-note-payoff': lazy(() =>
    import('./SaleOfAssetsNotePayoffFlow').then((module) => ({ default: module.SaleOfAssetsNotePayoffFlow })),
  ),
  'expense-payment': lazy(() =>
    import('./ExpensePaymentFlow').then((module) => ({ default: module.ExpensePaymentFlow })),
  ),
}
